Component=new Class(Observable,Autolayout,{useClosures:false,init:function(){arguments.callee.applySuper(this,arguments);this.initObject.apply(this,arguments);this.initSentinels();this.initEventListeners();this.initComponents();},destroy:function(){arguments.callee.applySuper(this,arguments);this.destroyComponents();this.destroyEventListeners();this.destroyObject();},initObject:function(element){this.element=DOM.getElement(element);if(!this.element)
throw typeof element=="string"?"no element: "+element:"no element";this.name=element;this.parent=null;this.components=[];this.sentinels=null;this.active=false;},destroyObject:function(element){this.components=null;this.sentinels=null;this.parent=null;this.element=null;this.name=null;},initEventListeners:function(){this.addEventListener(this.element,"mouseover","eventMouseOver");this.addEventListener(this.element,"mouseout","eventMouseOut");this.addEventListener(this.element,"mousemove","eventMouseMove");this.addEventListener(this.element,"mousedown","eventMouseDown");this.addEventListener(this.element,"mouseup","eventMouseUp");this.addEventListener(this.element,"click","eventClick");this.addEventListener(this.element,"dblclick","eventDoubleClick");this.addEventListener(this.element,"contextmenu","eventContextMenu");this.addEventListener(this.element,"keydown","eventKeyDown");this.addEventListener(this.element,"keyup","eventKeyUp");this.addEventListener(this.element,"keypress","eventKeyPress");this.addEventListener(this.element,"focus","eventFocus",true);this.addEventListener(this.element,"blur","eventBlur",true);this.addEventListener(this.element,"focusin","eventFocusIn");this.addEventListener(this.element,"focusout","eventFocusOut");},destroyEventListeners:function(){},addEventListener:function(object,eventName,methodName,useCapture){if(!this[methodName]||this[methodName]===Function.stub)
return;DOM.addEventListener(object,eventName,(this.useClosures?this.getEventListener(methodName):this.getIndirectEventListener(methodName)),useCapture);},removeEventListener:function(object,eventName,methodName,useCapture){var listener=this.useClosures?this.getEventListener(methodName):this.getIndirectEventListener(methodName);DOM.removeEventListener(object,eventName,listener,useCapture);},matchCommand:/(?:^|\s)command-(\S+)(?:\s|$)/,getMouseEventCommand:function(event,rootElement){var ancestors=DOM.getAncestors(event.target,true);var cmdattr=app.NAMESPACE+":command";for(var i=0;i<ancestors.length;i++){try{var result=ancestors[i].getAttribute(cmdattr);if(!result){result=this.matchCommand.exec(ancestors[i].className);if(result[1])
result=result[1];}
if(result){event.commandElement=ancestors[i];event.command=result.cssToJS();return event.command;}
if(ancestors[i]==rootElement)
break;}catch(e){}}},eventMouseDown:function(event){if(this.activatable)
this.activate(event);},eventFocus:function(event){if(this.activatable)
this.activate(event);},eventFocusIn:function(event){if(this.activatable)
this.activate(event);},reflow:function(event){this.applyAutolayouts(this.element);this.reflowComponents(event);},reflowComponents:function(event){this.components.forEach(function(component){component.reflow(event);});},initComponents:function(){},destroyComponents:function(){this.components.forEach(function(component){component.destroy();});this.components.length=0;},addComponent:function(component){this.components.add(component);component.parent=this;component.reflow();return component;},removeComponent:function(component){this.components.remove(component);component.parent=null;return component;},activatable:false,modal:false,initSentinels:function(){if(!this.activatable||this.sentinels)
return;this.sentinels={captureStart:DOM.createInvisibleInput()};this.element.insertBefore(this.sentinels.captureStart,this.element.firstChild);if(!this.modal)
return;extend(this.sentinels,{puntStart:DOM.createInvisibleInput(),captureEnd:DOM.createInvisibleInput(),puntEnd:DOM.createInvisibleInput()});this.element.insertBefore(this.sentinels.puntStart,this.element.firstChild);this.element.appendChild(this.sentinels.captureEnd);this.element.appendChild(this.sentinels.puntEnd);},refreshSentinels:function(){this.sentinels=null;this.initSentinels();},activate:function(event){if(!this.activatable)
return;if(!window.app.setActiveComponent(this))
return;this.active=true;this.captureFocus(event);DOM.addClassName(this.element,"active-component");this.broadcastToObserversNB("componentActivated",this);},deactivate:function(){this.active=false;DOM.removeClassName(this.element,"active-component");this.broadcastToObserversNB("componentDeactivated",this);},focusableTagNames:{taginput:defined,tagtextarea:defined,tagbutton:defined,tagselect:defined,tagdiv:defined,taga:defined,tagoption:defined,tagp:defined},captureFocus:function(event){if(this.active&&!this.modal)
return;var tagName=(defined(event)&&event.target.tagName)?"tag"+event.target.tagName.toLowerCase():null;var command;if(tagName&&event)
command=this.getMouseEventCommand(event);if(!tagName||(this.focusableTagNames[tagName]!==defined)&&!command){try{this.sentinels.captureStart.focus();event.stop();if(defined(this.sentinels.captureStart.focusIn))
this.sentinels.captureStart.focusIn();}catch(e){}}
if(!defined(event)||!this.modal)
return;try{if(event.target===this.sentinels.puntEnd)
this.sentinels.captureStart.focus();else if(event.target===this.sentinels.puntStart)
this.sentinels.captureEnd.focus();}catch(e){}},hide:function(){DOM.removeClassName(this.element,"visible");DOM.addClassName(this.element,"hidden");},show:function(){DOM.removeClassName(this.element,"hidden");DOM.addClassName(this.element,"visible");this.reflow();}});Modal=new Class(Component,{activatable:true,modal:true,isOpen:false,open:function(data,callback){if(!this.transitory)
window.scrollTo(0,0);this.data=defined(data)?data:{};this.callback=callback;this.active=false;this.isOpen=true;window.app.addModal(this);},close:function(data){window.app.removeModal(this);this.isOpen=false;if(this.callback)
this.callback(data,this);this.callback=null;this.data=null;},eventClick:function(event){if(event.shiftKey)
event.stop();},eventKeyPress:function(event){switch(event.keyCode){case 27:this.close(false);}}});Transient=new Class(Modal,{transitory:true,eventKeyPress:function(event){switch(event.keyCode){case 27:this.close(false);}},eventClick:function(event){this.close(this.getMouseEventCommand(event));return event.stop();},eventContextMenu:function(event){return event.stop();},open:function(data,callback,targetElement){this.targetElement=targetElement;return arguments.callee.applySuper(this,arguments);}});Component.Delegator={DEFAULT_NAMESPACE:"core",setupDelegates:function(object){if(!this.delegateListeners)
this.delegateListeners={};if(!this.delegates)
this.delegates={};if(!defined(this.NAMESPACE))
this.NAMESPACE=(window.app&&app.NAMESPACE)?app.NAMESPACE:this.DEFAULT_NAMESPACE;},addEventListener:function(object,eventName,methodName,useCapture){DOM.addEventListener(object,eventName,(this.useClosures?this.getEventListener(methodName):this.getIndirectEventListener(methodName)),useCapture);},setDelegate:function(name,object){this.setupDelegates(object);this.delegates[name]=object;return object;},setDelegateListener:function(eventName,delegateName){this.setupDelegates();this.delegateListeners[eventName]=delegateName;},delegateEvent:function(event,eventName){var delegate=DOM.getMouseEventAttribute(event,this.NAMESPACE+":delegate");if(!delegate){if(this.delegateListeners&&this.delegateListeners.hasOwnProperty(eventName))
delegate=this.delegateListeners[eventName];else
return undefined;}else
delegate=delegate.cssToJS();if(this.delegates&&this.delegates.hasOwnProperty(delegate)&&this.delegates[delegate][eventName])
return this.delegates[delegate][eventName](event,this);},getIndirectEventListener:function(methodName){if(!this.indirectEventListeners)
this.indirectEventListeners={};var method=this[methodName];var indirectIndex=this.getIndirectIndex();if(!this.indirectEventListeners[methodName]){return this.indirectEventListeners[methodName]=new Function("event","if ( window.indirectObjects === undefined ) return;"+
"try { event = Event.prep( event ); } catch( e ) {}"+
"var o = window.indirectObjects["+indirectIndex+"];"+
"if ( !o ) return;"+
"var r = o.delegateEvent( event, '"+methodName+
"' ); if ( r ) return r; if ( o[ '"+methodName+
"' ] ) return o['"+methodName+"'].call( o, event );");}
return this.indirectEventListeners[methodName];}};